"""empty message

Revision ID: aa091928b69f
Revises: 
Create Date: 2022-01-19 13:56:01.316355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa091928b69f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=20), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('motor', sa.String(length=10), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('nacional', sa.Boolean(), nullable=False),
    sa.Column('importada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=20), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('motor', sa.String(length=10), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('nacional', sa.Boolean(), nullable=False),
    sa.Column('importada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('endereço', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=False),
    sa.Column('preco_frete', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('cupom_desconto', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cupom', sa.Integer(), nullable=False),
    sa.Column('valor_desconto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('preco_frete', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'preco_frete', 'preco_total')
    )
    op.create_table('carroscarrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('carros_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['carros_id'], ['carros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoscarrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('motos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['motos_id'], ['motos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_pedidos_carroscarrinho',
    sa.Column('carroscarrinho', sa.Integer(), nullable=True),
    sa.Column('pedidos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carroscarrinho'], ['carroscarrinho.id'], ),
    sa.ForeignKeyConstraint(['pedidos'], ['pedidos.id'], )
    )
    op.create_table('association_pedidos_motoscarrinho',
    sa.Column('motoscarrinho', sa.Integer(), nullable=True),
    sa.Column('pedidos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motoscarrinho'], ['motoscarrinho.id'], ),
    sa.ForeignKeyConstraint(['pedidos'], ['pedidos.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_pedidos_motoscarrinho')
    op.drop_table('association_pedidos_carroscarrinho')
    op.drop_table('motoscarrinho')
    op.drop_table('carroscarrinho')
    op.drop_table('pedidos')
    op.drop_table('cupons')
    op.drop_table('carrinho')
    op.drop_table('usuario')
    op.drop_table('motos')
    op.drop_table('carros')
    # ### end Alembic commands ###
